# NumPy Array


In [ ]:
import numpy as np

In [ ]:
arr = np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# NumPy Array Size

In [ ]:
arr.size

9

# Numpy Array Shape

In [ ]:
arr.shape

(3, 3)

# NumPy Mathematical Funtions

In [ ]:
print(arr+array)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
np.add(arr, array)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
np.subtract(arr, array)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.divide(arr, array)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.multiply(arr, array)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [ ]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [ ]:
np.mean(arr)

5.0

In [ ]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
np.std(arr)

2.581988897471611

In [ ]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [ ]:
np.log(arr)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [ ]:
np.log10(arr)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

# NumPy Trigonomatric Funtions

In [ ]:
#np.sin(arr)
np.sin(20)

0.9129452507276277

In [ ]:
#np.cos(arr)
np.cos(20)

0.40808206181339196

In [ ]:
#np.tan(arr)
np.tan(20)

2.237160944224742

# NumPy Random

In [ ]:
# We create an unsorted rank 1 ndarray
np.random.randint(1,11,size=(10,))

array([ 9,  2,  7,  6,  3,  7,  3,  5,  7, 10])

In [ ]:
np.random.rand(100000)

array([0.2163532 , 0.74928123, 0.62379019, ..., 0.35909187, 0.62457596,
       0.84574051])

In [ ]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
np.random.random((3,3))

array([[0.32744976, 0.64691614, 0.54828316],
       [0.68543105, 0.74082447, 0.55371209],
       [0.0919101 , 0.0556084 , 0.13382214]])

In [ ]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
np.random.randint(4,15,size=(3,2))

array([[10, 13],
       [14,  9],
       [ 4, 11]])

In [ ]:
np.random.uniform(10,20)

12.022006586147285

In [ ]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0, 0.1, size=(1000,1000))